server:
 port: 8080
 servlet:
     context-path: /accounts

management:
   endpoints:
      web:
       exposure:
        include: "*"

spring:
 application:
    name: accounts
 config:
  import: optional:configserver:http://localhost:8071/

 rabbitmq:
    host: localhost
    port: 5672
    username: "guest"
    password: "guest"
    virtual-host: /